version: '3.9'

services:
  trader:
    build: './trader'
    ports: 
      - 5001:5000
    environment: 
        CRYPTOCOMPARE_TOKEN: ${CRYPTOCOMPARE_TOKEN}
        TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080